//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CASSCAID_TestEntities : DbContext
    {
        public CASSCAID_TestEntities()
            : base("name=CASSCAID_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ContentAuthorMapping> ContentAuthorMappings { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<ContentTopicMapping> ContentTopicMappings { get; set; }
        public virtual DbSet<EmailBox> EmailBoxes { get; set; }
        public virtual DbSet<RSSFeed> RSSFeeds { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<TopicType> TopicTypes { get; set; }
        public virtual DbSet<WebsiteRSSFeedMapping> WebsiteRSSFeedMappings { get; set; }
        public virtual DbSet<Website> Websites { get; set; }
    }
}
