//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentTopicMapping
    {
        public ContentTopicMapping()
        {
            this.Contents = new HashSet<Content>();
            this.Topics = new HashSet<Topic>();
        }
    
        public int ContentTopicMappingID { get; set; }
        public string ContentID { get; set; }
        public string TopicID { get; set; }
    
        public virtual ICollection<Content> Contents { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
