//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentAuthorMapping
    {
        public ContentAuthorMapping()
        {
            this.Contents = new HashSet<Content>();
        }
    
        public int ContentAuthorMappingID { get; set; }
        public string AuthorID { get; set; }
        public string ContentID { get; set; }
        public int ContentContentID { get; set; }
        public int Author_AuthorID { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<Content> Contents { get; set; }
    }
}
