//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ContentID { get; set; }
        public string Abstract { get; set; }
        public int ContentTopicMappingContentMappingID { get; set; }
        public int ContentAuthorMappingContentAuthorID { get; set; }
        public int ContentTopicMappingContentMapID { get; set; }
        public int ContentTopicMappingContentMapID1 { get; set; }
        public int ContentAuthorMapping_ContentAuthorID { get; set; }
    
        public virtual ContentAuthorMapping ContentAuthorMapping { get; set; }
        public virtual ContentTopicMapping ContentTopicMapping { get; set; }
    }
}
