//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailBox
    {
        public EmailBox()
        {
            this.WebsiteRSSFeedMappings = new HashSet<WebsiteRSSFeedMapping>();
        }
    
        public int EmailBoxID { get; set; }
        public string MailboxName { get; set; }
        public string MailboxAddress { get; set; }
        public string EmailAlert { get; set; }
        public int WebsiteRSSFeedMappingWebsiteFeedMapping { get; set; }
    
        public virtual ICollection<WebsiteRSSFeedMapping> WebsiteRSSFeedMappings { get; set; }
    }
}
