//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSSFeed
    {
        public RSSFeed()
        {
            this.WebsiteRSSFeedMappings = new HashSet<WebsiteRSSFeedMapping>();
        }
    
        public int RSSFeedID { get; set; }
        public string RSSFeedName { get; set; }
        public string FeedURL { get; set; }
        public string FeedAlert { get; set; }
        public string Feed_Description { get; set; }
        public System.DateTime Feed_Publication_Date { get; set; }
        public string Feed_PermaLink { get; set; }
    
        public virtual ICollection<WebsiteRSSFeedMapping> WebsiteRSSFeedMappings { get; set; }
    }
}
