//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Topics = new HashSet<Topic>();
        }
    
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string TeamPage { get; set; }
        public string TeamRequest { get; set; }
        public string TopicID { get; set; }
    
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
