//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicType
    {
        public int TopicTypeID { get; set; }
        public string TopicTypeName { get; set; }
        public string CategoryID { get; set; }
        public string TopicsTopicID { get; set; }
        public int Topics_TopicID { get; set; }
        public int Category_CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
