//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.TopicTypes = new HashSet<TopicType>();
            this.ContentTopicMappings = new HashSet<ContentTopicMapping>();
            this.Teams = new HashSet<Team>();
        }
    
        public int TopicID { get; set; }
        public string TopicName { get; set; }
        public string TopicTypeID { get; set; }
        public string LinkDocument { get; set; }
        public string TeamRequest { get; set; }
        public string TeamID { get; set; }
        public int TeamTeamID { get; set; }
        public int WebsiteRSSFeedMappingWebsiteFeedMapping { get; set; }
    
        public virtual ICollection<TopicType> TopicTypes { get; set; }
        public virtual WebsiteRSSFeedMapping WebsiteRSSFeedMapping { get; set; }
        public virtual ICollection<ContentTopicMapping> ContentTopicMappings { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}
