//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website
    {
        public Website()
        {
            this.WebsiteRSSFeedMappings = new HashSet<WebsiteRSSFeedMapping>();
        }
    
        public int WebsiteID { get; set; }
        public string WebsiteName { get; set; }
        public string WebsiteURL { get; set; }
    
        public virtual ICollection<WebsiteRSSFeedMapping> WebsiteRSSFeedMappings { get; set; }
    }
}
